services:
  - type: web
    name: ingres-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.app.main:app -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_NAME
        value: ingres_db
      - key: MONGO_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: PYTHONPATH
        value: .
